version: '3.9'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: xenodochial_wescoff
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=messenger_crypter
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  pg_data:
